"""Compatibility helpers for Isaac Lab Mimic generation runs."""

from __future__ import annotations

import asyncio
import contextlib
from collections.abc import Callable

import torch


def wrap_generation_env_loop(original_env_loop: Callable) -> Callable:
    """Wrap Isaac Lab Mimic's env loop with a project-local failure cap.

    Isaac Lab's generator treats ``generation_guarantee=True`` as "keep trying until N successes".
    In the version vendored with this project, ``datagen_config.max_num_failures`` is not checked in the
    main loop. When a task is misconfigured and success rate is 0%, failed episodes can grow forever. This
    wrapper preserves the upstream loop behavior and adds the missing failure-limit exit.
    """

    def env_loop(env, env_reset_queue, env_action_queue, shared_datagen_info_pool, asyncio_event_loop):
        import isaaclab_mimic.datagen.generation as generation

        env_id_tensor = torch.tensor([0], dtype=torch.int64, device=env.device)
        prev_num_attempts = generation.num_attempts
        max_num_failures = int(getattr(env.cfg.datagen_config, "max_num_failures", 0) or 0)

        with contextlib.suppress(KeyboardInterrupt), torch.inference_mode():
            while True:
                while env_action_queue.qsize() != env.num_envs:
                    asyncio_event_loop.run_until_complete(asyncio.sleep(0))
                    while not env_reset_queue.empty():
                        env_id_tensor[0] = env_reset_queue.get_nowait()
                        env.reset(env_ids=env_id_tensor)
                        env_reset_queue.task_done()

                actions = torch.zeros(env.action_space.shape)

                for _ in range(env.num_envs):
                    env_id, action = asyncio_event_loop.run_until_complete(env_action_queue.get())
                    actions[env_id] = action

                env.step(actions)

                for _ in range(env.num_envs):
                    env_action_queue.task_done()

                if prev_num_attempts != generation.num_attempts:
                    prev_num_attempts = generation.num_attempts
                    success_rate = (
                        100 * generation.num_success / generation.num_attempts
                        if generation.num_attempts > 0
                        else 0.0
                    )
                    print("")
                    print("*" * 50, "\033[K")
                    print(
                        f"{generation.num_success}/{generation.num_attempts} ({success_rate:.1f}%) "
                        "successful demos generated by mimic\033[K"
                    )
                    print("*" * 50, "\033[K")

                    generation_guarantee = env.cfg.datagen_config.generation_guarantee
                    generation_num_trials = env.cfg.datagen_config.generation_num_trials
                    check_val = generation.num_success if generation_guarantee else generation.num_attempts
                    if check_val >= generation_num_trials:
                        print(f"Reached {generation_num_trials} successes/attempts. Exiting.")
                        break
                    if max_num_failures > 0 and generation.num_failures >= max_num_failures:
                        print(
                            f"Reached max_num_failures={max_num_failures} "
                            f"({generation.num_success} successes, {generation.num_failures} failures). Exiting."
                        )
                        break

                if env.sim.is_stopped():
                    break

        env.close()

    return env_loop

